import dataclasses


@dataclasses.dataclass
class Colour:
    """Collection of colours that are used by MDSuite

    Names generated by https://www.htmlcsscolor.com
    """

    PRUSSIAN_BLUE = "#003F5C"
    MULBERRY = "#BC5090"
    ORANGE = "#BC5090"
    PAUA = "#2E294E"
